# Part III: Data Wrangling

This part of the textbook covers topics related to working with data. 
Every data set is messy in its own way [@tidy-data], and this section is focused on providing you with some of the tools to deal with the most common types of messy data.

@sec-data-input covers how to read in data from many common formats, such as spreadsheets, web tables, and databases.

@sec-basic-data-vis provides a brief primer on how to create different charts and graphics in R and python for use in other sections.

@sec-data-cleaning covers verbs for transforming data - creating new variables, modifying existing variables, selecting specific rows and/or columns, and more.

@sec-strings discusses string manipulations. Text data is some of the messiest data out there, and this chapter will give you some tools to help make textual data more tidy.

@sec-data-reshape discusses how to transform data from wide human-friendly formats to long comptuer-friendly formats for analysis and processing.

@sec-data-join discusses how to join data sets together using common variables.

@sec-datetime discusses how to work with dates and times using R and Python.

@sec-lists discusses how to work with data stored in nested lists efficiently.

@sec-spatial covers working with spatial data formats: drawing maps, working with spatial regions, and more. We will focus exclusively on the visualization and data wrangling part, leaving the modeling of spatial data for a different time. 

## References {#sec-wrangling-refs}