project:
  type: book
  output-dir: docs
  execute-dir: file
  preview:
    port: 3430
    browser: true
  post-render:
    - ./validate.sh

date: today
date-format: long

from: markdown+emoji

book:
  title: "Statistical Computing using R and Python"
  author: "Susan Vanderplas"
  issued: today
  output-file: full-book
  favicon: build_deps/favicon.ico
  cover-image: build_deps/cover.png
  cover-image-alt: "Cover image for Statistical Computing using R and Python. Shows little fuzzball 'monsters' completing data-related tasks such as rearranging data frames, brewing complete documents using markdown, and assembling data analyses by arranging, wrangling, visualizing, and modeling data. Images assembled from a collection of drawings by Allison Horst; used with permission."
  public-url: "https://srvanderplas.github.io/stat-computing-r-python/"
  site-url: "https://srvanderplas.github.io/stat-computing-r-python/"
  repo-url: "https://github.com/srvanderplas/stat-computing-r-python/"
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  search: true
  google-analytics: "G-4ZFBDKXJXP"
  language: english
  reader-mode: true
  type: book
  medium: ebook
  isbn: 978-1-60962-358-6
  doi: https://doi.org/10.32873/unl.dc.024
  sidebar:
    style: floating
  page-footer:
    left: "Copyright 2025, Susan Vanderplas"
    right:
      - icon: github
        href: "https://github.com/srvanderplas"
        aria-label: GitHub
  comments:
    giscus:
      repo: srvanderplas/stat-computing-r-python
      category: "General"
      mapping: "pathname"
  chapters:
    - index.qmd

    - part: part-tools/00-tools-intro.qmd
      chapters:
        - part-tools/01-computer-basics.qmd
        - part-tools/02-setting-up-computer.qmd
        - part-tools/03-Rstudio-interface.qmd
        - part-tools/04-scripts-notebooks.qmd
        - part-tools/05-git-and-github.qmd
        - part-tools/06-documents.qmd

    - part: part-gen-prog/00-gen-prog.qmd
      chapters:
        - part-gen-prog/00-intro.qmd
        - part-gen-prog/01-basic-var-types.qmd
        - part-gen-prog/01a-math-logical-operators.qmd
        - part-gen-prog/02-prog-functions.qmd
        - part-gen-prog/03-data-struct.qmd
        - part-gen-prog/035-matrix-calcs.qmd
        - part-gen-prog/04-control-struct.qmd
        - part-gen-prog/05-functions.qmd
        - part-gen-prog/06-debugging.qmd
        - part-gen-prog/07-prog-data.qmd

    - part: part-wrangling/00-wrangling.qmd
      chapters:
        - part-wrangling/01-data-input.qmd
        - part-wrangling/02-basic-data-vis.qmd
        - part-wrangling/02a-eda.qmd
        - part-wrangling/02b-graphics.qmd
        - part-wrangling/02c-good-graphics.qmd
        - part-wrangling/03-data-cleaning.qmd
        - part-wrangling/04-strings.qmd
        - part-wrangling/05-data-reshape.qmd
        - part-wrangling/05b-normal-forms.qmd
        - part-wrangling/06-data-join.qmd
        - part-wrangling/07-datetime.qmd
        - part-wrangling/08-functional-prog.qmd

    - part: part-advanced-topics/00-advanced.qmd
      chapters:
        - part-advanced-topics/01-simulation.qmd
        - part-advanced-topics/02-data-doc.qmd
        - part-advanced-topics/03-web-scraping.qmd
        - part-advanced-topics/04-xml-json-list-processing.qmd
        - part-advanced-topics/05-APIs.qmd
        - part-advanced-topics/06-pdf-tools.qmd
        - part-advanced-topics/07-intro-interactive-graphics.qmd
        - part-advanced-topics/08-javascript-graphics.qmd
        - part-advanced-topics/09-big-data.qmd
        - part-advanced-topics/10-databases.qmd
        - part-advanced-topics/11-arrow-parquet.qmd
        - part-advanced-topics/12-memory-handling.qmd
        # - part-advanced-topics/13-spatial-formats.qmd
    - graveyard.qmd

bibliography:
  - references.bib
  - packages.bib
csl: build_deps/ieee-with-url.csl



custom-callout:
  demo:
    title: "Demo"
    icon-symbol: "fa-puzzle-piece"
    color: "#91d5d4"
    collapse: false
  example:
    title: "Example"
    icon-symbol: "fa-bicycle"
    color: "#f39c12"
    collapse: false
  advanced:
    icon-symbol: "fa-brain"
    color: "#cbbaf9"
    collapse: true
  learnmore:
    title: "Learn More"
    icon-symbol: "fa-book"
    color: "#f09bb6"
    collapse: true
  setup:
    title: "Setup"
    icon-symbol: "fa-hammer"
    color: "#f3e969"
    collapse: true
  diy:
    title: "Do It Yourself"
    icon-symbol: "fa-wrench"
    color: "#b3e094"
    collapse: false

collapse-callout:
  warning: false
  caution: true
  important: false
  tip: false
  note: true

filters:
  - custom-callout
  - collapse-callout
  - filters-fix.lua

format:
  html:
    page-layout: full
    grid:
      sidebar-width: 250px
      margin-width: 150px
      body-width: 1200px
    css: ['build_deps/style.css']
    highlight-style: a11y
    # theme:
    #   light: ['flatly', build_deps/_variables-flatly.scss, build_deps/theme.scss]
    #   dark: ['darkly', build_deps/_variables-darkly.scss, build_deps/theme.scss]
    code-link: true
    include-in-header: "build_deps/header.html"
    code-copy: true
    code-annotations: select

  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: "header.tex"

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true
    dpi: 300
    width: 60

execute:
  engine: knitr
  freeze: auto  # re-render only when source changes
