# Preface {.unnumbered}

## Acknowledgements

The cover of this book is an amalgam of different images by the lovely [\@allison_horst](https://github.com/allisonhorst), which are released under the [cc-by 4.0 license](https://github.com/allisonhorst/stats-illustrations/blob/main/license). I have modified them to remove most of the R package references and arrange them to represent the topics covered in this book.

<a href="https://www.flaticon.com/free-icons/laptop">Laptop icon used in the tab/logo created by Good Ware - Flaticon</a>

Throughout this book, I have borrowed liberally from other online tutorials, published books, and blog posts. I have tried to ensure that I link to the source material throughout the book and provide appropriate credit to anyone whose examples I have used, modified, or repurposed. Special thanks to the tutorials provided by Posit/RStudio and the tidyverse project.


I don't have official editors, but thank you to those who make use of the giscus comment box to let me know about issues and typos. So far, you've helped me fix at least `r 3` issues so far!



::: {.callout-note collapse=true}
## Tools 

This book was built with the following parameters/settings/library versions:

```{python}
#| eval: true
#| echo: true
#| cache: false

import os
import sys

itemlist = ["PWD", "SHELL", "USER", "PYTHONIOENCODING", "VIRTUAL_ENV", "RETICULATE_MINICONDA_PYTHON_ENVPATH", "RETICULATE_PYTHON_FALLBACK", "R_HOME", "R_PLATFORM", "LD_LIBRARY_PATH", "R_LIBS_USER", "R_LIBS_SITE","RENV_PROJECT", "RSTUDIO_PANDOC", "RMARKDOWN_MATHJAX_PATH", "R_SESSION_INITIALIZED", "PYTHONPATH"]

itemlist = list(set(itemlist) & set(os.environ))
itemlist.sort()

for item in itemlist:
    print(f'{item}{" : "}{os.environ[item]}')

print(sys.path)
```


```{R}
#| eval: true
#| echo: true
#| cache: false

library(devtools)
devtools::session_info()
```

:::