#!/bin/bash

# Update dependencies required by the book
pipdeptree -r --warn silence | grep -E '^\w+' > requirements.txt

# Install requirements
pip install -r requirements.txt

# Update package versions from what's installed
# pip --disable-pip-version-check list --outdated --format=json | \
# python -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))" | \
# xargs -n1 pip install -U