# Data Documentation {#sec-data-doc}

<!-- Outline modified from copilot record -->
<!-- https://copilot.microsoft.com/shares/Siv7qJ39iGCr2eS4Yf2D9 -->

## Objectives {-}

## Understanding Data

- Define metadata
- Why does metadata matter?
- Identify sources, formats, and collection information


## Elements of Data Documentation

- Descriptive Metadata (title, author, creation date, variables, units)

- Administrative Metadata (access permissions, licensing)

- Structural metadata (file format, schema, relationships between variables)

- Provenance Metadata (origin, transformations/processing, version history)

- Collection Documentation
  - Methods for how data was collected, standards, quality controls
  - information on critical inputs -- e.g. sourcing of chemicals for a process, seed batch numbers and manufacturing information, links to survey forms and code. 
  - Anything that may impact the statistical modeling process
  
## Tools and Standards

DataCite standards
Data dictionaries
README files
codebooks

automated documentation systems??

## Best Practices

- Version Control
- Documentation of processing and cleaning steps (and software, versions, environments)
- Logs of parameter settings and analysis code
- Links between data documentation and code documentation

## Case Studies and Examples

- Levels of documentation

- Failed reproducibility efforts

- Successful reproducibility efforts

## Data Documentation Checklist

