#### Demo: OAuth 2.0 with Google Maps Geocoding

Geocoding is the process of converting an address into a set of geographical coordinates (latitude/longidude). 
It's fairly common to have addresses in a database and need to do some sort of spatial analysis on those addresses, and since street addresses don't tell us much about general spatial location, geocoding is often an important step to get your data ready for a statistical analysis.

This requires using Google Cloud -- so you will need a Google account. You will also have to enable billing -- Google is pretty reasonable about letting you try out various APIs in a limited fashion, but it's always a bit scary to give a company payment information if you don't intend to pay them. 

Google https://developers.google.com/maps/documentation/geocoding/cloud-setup provides instructions on how to get an API key, and during the setup you will have the option to restrict your key to certain google APIs. 
I selected only Geocoding and geolocation for this API key -- you can always generate a different key to access other Google APIs.

Once you've gotten your API key and completed setup, navigate to [the geocoding code sample](https://console.cloud.google.com/google/maps-apis/discover/geocoding;filters=%7B%22useCaseFilters%22:%5B%22CURRENT_LOCATION%22%5D,%22platformFilters%22:%5B%5D,%22codeTypeFilters%22:%5B%5D%7D?inv=1&invt=Ab2ekw&project=phrasal-league-424319-m9). Don't worry that it's a lot of HTML/JavaScript -- 

