#!/bin/bash


quartofiles=$(find "." -type f -name "*.qmd")


# Get all images in any qmd file
grep -r '!\[.*\]\(.*\)' $quartofiles > all-images

grep -v 'fig-alt' all-images > fix-images

cat fix-images
