
# Setting Up Your Computer {#sec-setting-up}

## Objectives

1.  Set up RStudio, R, Quarto, and python
2.  Be able to run demo code in R and python

## Installation Process

In this section, I will provide you with links to set up various programs on your own machine. If you have trouble with these instructions or encounter an error, post on the class message board or contact me for help.

1.  Download and run the R installer for your operating system from CRAN:

    -   Windows: https://cran.rstudio.com/bin/windows/base/
    -   Mac: https://cran.rstudio.com/bin/macosx/
    -   Linux: https://cran.rstudio.com/bin/linux/ (pick your distribution)

    If you are on Windows, you should also install the [Rtools4 package](https://cran.rstudio.com/bin/windows/Rtools/); this will ensure you get fewer warnings later when installing packages.

    More detailed instructions for Windows are available [here](https://owi.usgs.gov/R/training-curriculum/installr/)

2.  Download and install the latest version of [python 3](https://www.python.org/downloads/)

    - Then, install Jupyter using the instructions [here](https://quarto.org/docs/getting-started/installation.html#jupyter)

    - [Additional instructions for installing Python 3](https://www.py4e.com/lessons/install) from Python for Everybody if you have trouble.

3.  Download and install the [latest version of RStudio](https://posit.co/download/rstudio-desktop/#download) for your operating system. RStudio is a integrated development environment (IDE) for R - it contains a set of tools designed to make writing R code easier.

4.  Download and install the [latest version of Quarto](https://quarto.org/#getting-started) for your operating system. Quarto is a command-line tool released by RStudio that allows Rstudio to work with python and other R specific tools in a unified way.

The following steps may be necessary depending on which class you're in. If you want to be safe, go ahead and complete these steps as well.

5. Install git using the instructions [here](https://happygitwithr.com/install-git.html). Consult the [troubleshooting guide](https://happygitwithr.com/troubleshooting.html) if you have issues. If that fails, then seek help in office hours.

6. Install LaTeX and rmarkdown:
    - Launch R, and type the following commands into the console:
```{r tinytex-install, eval = F}
install.packages(c("tinytex", "knitr", "rmarkdown", "quarto"))
library(tinytex)
install_tinytex()
```



::: callout-tip
### Your turn {.unnumbered}

Open RStudio on your computer and explore a bit.

-   Can you find the R console? Type in `2+2` to make sure the result is `4`.
-   Run the following code in the R console:

``` r
install.packages(
  c("tidyverse", "rmarkdown", "knitr", "quarto")
)
```

-   Can you find the text editor?
    -   Create a new quarto document (File -\> New File -\> Quarto Document).
    -   Paste in the contents of [this document](../files/getting-started-r-python.qmd).
    -   Compile the document (Ctrl/Cmd + Shift + K) and use the Viewer pane to see the result.
    -   If this all worked, you have RStudio, Quarto, R, and Python set up correctly on your machine.

:::


