#!/bin/bash

# From https://stackoverflow.com/a/13038235/2859168
set_union () {
   sort $1 $2 | uniq
}

set_intersection () {
   sort $1 $2 | uniq -d
}

set_difference () {
   sort $1 $2 $2 | uniq -u
}

set_symmetric_difference() {
   sort $1 $2 | uniq -u
}

FindRequirements() {
  grep -r "from .* import .*" --include "*.qmd" . | awk '{ match( $0, /:from ([A-z0-9\[\]]*).?.*? import .*$/, arr) ; if(arr[1] != "") print arr[1] } ' | sort | uniq > setup/py-imports
  grep -r "import .* as .*" --include "*.qmd" . | awk '{ match( $0, /:import ([A-z0-9\[\]]*).?.*? as .*$/, arr) ; if(arr[1] != "") print arr[1] } ' | sort | uniq >> pyenv/py-imports
  grep -r "import .*" --include "*.qmd" . | awk '{ match( $0, /:import ([A-z0-9\[\]]*).*$/, arr) ; if(arr[1] != "") print arr[1] } ' | sort | uniq >> setup/py-imports
  pipdeptree -r -f --warn silence | awk -F'=+' '{ print $1 }' | sed -e 's/ *//g' | sort | uniq -i >> setup/py-imports

  # deduplicate
  cat setup/requirements.txt >> setup/py-imports
  cat setup/py-deps-reqs >> setup/py-imports
  cat setup/py-imports | sort | uniq -i  > setup/py-imports-clean

  # replace PIL with pillow... ugh python sucks
  sed -i -e 's/^PIL$/pillow/g' setup/py-imports-clean
  # replace sklearn with scikit-learn
  sed -i -e 's/^sklearn$/scikit-learn/g' setup/py-imports-clean
  # replace cv2 with opencv
  sed -i -e 's/^cv2/opencv/g' setup/py-imports-clean
  # replace tabula with tabula-py
  sed -i -e 's/^tabula$/tabula-py/g' setup/py-imports-clean
  # replace camelot with camelot-py
  sed -i -e 's/^camelot$/camelot-py/g' setup/py-imports-clean
  # replace . and _ with -
  sed -i -e 's/[\._]/-/g' setup/py-imports-clean


  cat setup/py-imports-clean | sort | uniq -i  > setup/py-imports-clean-sort


  # Python system packages assembled from here: https://docs.python.org/3/library/index.html
  # Need to not install these, since python/pip will error out :(
  set_difference setup/py-imports-clean-sort setup/py-system-pkgs > setup/py-imports-install

  # Remove temp files created when assembling packages
  rm setup/py-imports #setup/py-imports-clean

  mv setup/py-imports-install setup/requirements.txt
}

SetRequirements() {
  # Update dependencies required by the book
  # pipdeptree -r -f --warn silence | grep -E '^[a-zA-Z0-9\-]+' > requirements.txt
  pip-chill --no-version > setup/requirements.txt
  FindRequirements

  echo "Requirements file updated successfully!"
}


Install() {
  # Install requirements
  pip3 install -r setup/requirements.txt
  echo "Packages in requirements.txt installed with pip"
}


Update() {
  # Update package versions from what's installed
  pip3 --disable-pip-version-check list --outdated --format=json | \
  python -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))" | \
  xargs -n1 pip3 install -U
  echo "Package version update complete"

  SetRequirements
}


Help() {
  echo "Handle book's python dependencies."
  echo
  echo "Syntax: py-deps [-h|i|s|u]"
  echo "Options:"
  echo "h   Print the help text"
  echo "i   pip install packages from requirements.txt file"
  echo "s   Set requirements - examine all qmd files for python deps and update requirements.txt accordingly."
  echo "u   Update all python package versions required by pip. Will also set requirements to updated versions."
  echo
}

while getopts ":hisu" option; do
  case $option in
    h) # display Help
      Help
      exit;;
    i) # install pkgs
      Install
      exit;;
    s) # set requirements file
      SetRequirements
      exit;;
    u) # update python pkgs
      Update
      exit;;
    \?) # invalid option
      echo "Error: Invalid option"
      exit;;
  esac
done
