erDiagram
  EMPLOYEE {
    int ID PK
    string first
    string last
    string middle
    string address
    string phone
    int ssn
  }
  BACKGROUND_CHECK {
    int ID PK
    int EMPLOYEE_ID FK
    date date
    string results
  }
  TAX_INFO {
    int ID PK
    int EMPLOYEE_ID FK
    int year
    float withholding
  }
  TRAINING {
    int ID PK
    int TRAINING_TYPE
    int EMPLOYEE_ID FK
    float score
  }
  EMP_AGREE {
    int ID PK
    int EMPLOYEE_ID FK
    int POSITION_ID FK
    int POSITION_TYPE
    date START_DATE
    date END_DATE
    int benefits_class
    float pay_hourly_equiv
    float hours_wk
    int pay_period
  }
  ORG_REL {
    int ID PK
    int EMPLOYEE_ID FK
    int SUPERVISOR_ID FK
  }
  EMPLOYEE }|--|| EMP_AGREE : has
  EMPLOYEE }|--|| ORG_REL : has
  EMPLOYEE ||--|{ TAX_INFO : has
  EMPLOYEE ||--|{ TRAINING : has
  EMPLOYEE ||--|{ BACKGROUND_CHECK : has


  accTitle: Sample Company Employee-related Records
  accDescr {
    This diagram contains information about corporate records relating to a single employee, such as employee details, supervisory relationships, employment agreement details, training records, tax information, and background checks.
  }