graph TD

%% Meredith Grey
MeredithGrey -- romantic --> DerekShepherd
MeredithGrey -- romantic --> NathanRiggs
MeredithGrey -- romantic --> AndrewDeLuca
MeredithGrey -- romantic --> NickMarsh
MeredithGrey -- one-night --> GeorgeOMalley
MeredithGrey -- one-night --> SteveMurphy
MeredithGrey -- one-night --> WilliamThorpe
MeredithGrey -- one-night --> FinnDandridge

%% Cristina Yang
CristinaYang -- romantic --> OwenHunt
CristinaYang -- romantic --> PrestonBurke
CristinaYang -- one-night --> ShaneRoss

%% Owen Hunt
OwenHunt -- romantic --> CristinaYang
OwenHunt -- romantic --> AmeliaShepherd
OwenHunt -- romantic --> TeddyAltman
OwenHunt -- flirtation --> EmmaMarling

%% Alex Karev
AlexKarev -- romantic --> IzzieStevens
AlexKarev -- romantic --> JoWilson
AlexKarev -- one-night --> LexieGrey
AlexKarev -- one-night --> OliviaHarper
AlexKarev -- one-night --> RebeccaPope

%% Izzie Stevens
IzzieStevens -- romantic --> AlexKarev
IzzieStevens -- romantic --> DennyDuquette
IzzieStevens -- romantic --> GeorgeOMalley

%% George O'Malley
GeorgeOMalley -- romantic --> CallieTorres
GeorgeOMalley -- one-night --> MeredithGrey
GeorgeOMalley -- romantic --> IzzieStevens
GeorgeOMalley -- one-night --> OliviaHarper

%% Callie Torres
CallieTorres -- romantic --> GeorgeOMalley
CallieTorres -- romantic --> EricaHahn
CallieTorres -- romantic --> ArizonaRobbins
CallieTorres -- one-night --> MarkSloan
CallieTorres -- one-night --> PennyBlake

%% Arizona Robbins
ArizonaRobbins -- romantic --> CallieTorres
ArizonaRobbins -- flirtation --> LaurenBoswell
ArizonaRobbins -- flirtation --> CarinaDeLuca

%% Mark Sloan
MarkSloan -- romantic --> LexieGrey
MarkSloan -- flirtation --> AddisonMontgomery
MarkSloan -- one-night --> CallieTorres
MarkSloan -- one-night --> TeddyAltman
MarkSloan -- one-night --> ReedAdamson

%% Lexie Grey
LexieGrey -- romantic --> MarkSloan
LexieGrey -- romantic --> JacksonAvery
LexieGrey -- one-night --> AlexKarev

%% Jackson Avery
JacksonAvery -- romantic --> LexieGrey
JacksonAvery -- romantic --> AprilKepner
JacksonAvery -- romantic --> MaggiePierce
JacksonAvery -- one-night --> JoWilson

%% April Kepner
AprilKepner -- romantic --> JacksonAvery
AprilKepner -- romantic --> MatthewTaylor

%% Jo Wilson
JoWilson -- romantic --> AlexKarev
JoWilson -- romantic --> JasonMyers
JoWilson -- one-night --> JacksonAvery

%% Andrew DeLuca
AndrewDeLuca -- romantic --> MaggiePierce
AndrewDeLuca -- romantic --> MeredithGrey

%% Amelia Shepherd
AmeliaShepherd -- romantic --> OwenHunt
AmeliaShepherd -- romantic --> AtticusLincoln
AmeliaShepherd -- romantic --> KaiBartley

%% Maggie Pierce
MaggiePierce -- romantic --> AndrewDeLuca
MaggiePierce -- romantic --> JacksonAvery
MaggiePierce -- romantic --> WinstonNdugu

%% Teddy Altman
TeddyAltman -- romantic --> OwenHunt
TeddyAltman -- romantic --> TomKoracick
TeddyAltman -- one-night --> MarkSloan

%% Erica Hahn
EricaHahn -- romantic --> CallieTorres

%% Preston Burke
PrestonBurke -- romantic --> CristinaYang

%% Nathan Riggs
NathanRiggs -- romantic --> MeredithGrey
NathanRiggs -- romantic --> MeganHunt

%% Levi Schmitt
LeviSchmitt -- romantic --> NicoKim

%% Nico Kim
NicoKim -- romantic --> LeviSchmitt

%% Miranda Bailey
MirandaBailey -- romantic --> BenWarren

%% Ben Warren
BenWarren -- romantic --> MirandaBailey

%% Richard Webber
RichardWebber -- romantic --> EllisGrey
RichardWebber -- romantic --> CatherineFox

%% Ellis Grey
EllisGrey -- romantic --> RichardWebber

%% Catherine Fox
CatherineFox -- romantic --> RichardWebber

%% Tom Koracick
TomKoracick -- romantic --> TeddyAltman

%% Atticus Lincoln
AtticusLincoln -- romantic --> AmeliaShepherd

%% Nick Marsh
NickMarsh -- romantic --> MeredithGrey
