---
config:
  layout: elk
---
flowchart TD
    Lisp["Lisp"] --> Smalltalk["Smalltalk"]
    Algol["Algol"] --> C["C"] & Pascal["Pascal"]
    C --> C++["C++"] & ObjectiveC["ObjectiveC"] & Go["Go"]
    C++ --> Java["Java"]
    Java --> C#["C#"] & Scala["Scala"] & Kotlin["Kotlin"]
    Smalltalk --> ObjectiveC
    Perl["Perl"] --> Ruby["Ruby"]
    ML["ML"] --> Haskell["Haskell"]
    Scheme["Scheme"] --> JavaScript["JavaScript"]
    ObjectiveC --> Swift["Swift"]
    S["S"] --> R["R"]
    Fortran["Fortran"] -.-> Algol & SAS["SAS"] & S
    Smalltalk -.-> C++ & Java & Ruby
    Perl -.-> Python["Python"]
    Lisp -.-> Python & R & Julia["Julia"] & S
    C -.-> Python
    Haskell -.-> Scala
    C++ -.-> Rust["Rust"]
    ML -.-> Rust
    Rust -.-> Swift
    Java -.-> JavaScript
    SAS -.-> R
    Python -.-> Julia
    R -.-> Julia
    UnixShell["UnixShell"] -.-> S
    GLIMSPSS["GLIMSPSS"] -.-> S
